# Generated by Django 2.1.7 on 2019-04-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.TextField(verbose_name='文章')),
                ('author', models.CharField(max_length=30, verbose_name='作者')),
            ],
        ),
    ]
