# Generated by Django 2.1.7 on 2019-04-27 02:48

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0004_auto_20190426_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, verbose_name='姓名')),
                ('Description', DjangoUeditor.models.UEditorField(blank=True, verbose_name='描述')),
                ('ImagePath', models.CharField(blank=True, max_length=100, verbose_name='图片目录')),
                ('Content', DjangoUeditor.models.UEditorField(blank=True, default='test', verbose_name='内容')),
            ],
        ),
    ]
